"""
create_yaml.py
- สร้างไฟล์ .yaml ที่จำเป็นสำหรับเทรน YOLO
- (เวอร์ชันแก้ไข) สร้างชื่อทดแทน (placeholder names) 'class_0', 'class_1', ...
- เนื่องจากไฟล์ Meta.csv ไม่มีคอลัมน์ 'SignName'
"""
import os
import pandas as pd

# --- การตั้งค่า ---
YOLO_DATA_DIR = os.path.join("data", "gtsrb_yolo") # โฟลเดอร์จากขั้นตอนที่ 1
OUTPUT_YAML = os.path.join("data", "gtsrb-yolo.yaml") # ไฟล์ config ที่เราจะสร้าง
NUM_CLASSES = 43 # ชุดข้อมูล GTSRB มี 43 คลาส (0-42)

print("--- Generating YAML config with placeholder names ---")

# --- สร้าง Class Names ทดแทน (Placeholder) ---
# เราจะสร้างชื่อ 'class_0', 'class_1', ..., 'class_42'
# เพราะ Meta.csv ของคุณไม่มีชื่อป้ายจริงๆ
try:
    class_names = {i: f'class_{i}' for i in range(NUM_CLASSES)}
    print(f"Successfully generated {len(class_names)} placeholder class names.")
except Exception as e:
    print(f"Error generating class names: {e}")
    exit()

# --- เขียนไฟล์ .yaml ---
# หาย path แบบเต็ม (Absolute Path) ไปยังโฟลเดอร์ data
try:
    abs_data_path = os.path.abspath(YOLO_DATA_DIR)
    if not os.path.exists(abs_data_path):
        print(f"Error: YOLO data directory not found at: {abs_data_path}")
        print("Did step 1 (convert_gtsrb_to_yolo.py) run successfully?")
        exit()
except Exception as e:
    print(f"Error getting absolute path: {e}")
    exit()

yaml_content = f"""
# YOLOv8 dataset config file
# This file was auto-generated by create_yaml.py (using placeholder names)

path: {abs_data_path.replace(os.path.sep, '/')}
train: images/train  # train images (relative to 'path')
val: images/val      # val images (relative to 'path')

# Classes
nc: {NUM_CLASSES}  # number of classes
names: {class_names} # dictionary of class names
"""

# บันทึกไฟล์
try:
    with open(OUTPUT_YAML, "w", encoding="utf-8") as f:
        f.write(yaml_content)
    print(f"\n✅ Successfully created YOLO config file at: {OUTPUT_YAML}")
    print("Note: Using placeholder names (e.g., 'class_0') because 'SignName' was not found in Meta.csv.")
except Exception as e:
    print(f"Error writing YAML file: {e}")